import './globals.css'
import {Inter} from 'next/font/google'
import clsx from 'clsx'
import NavMenu from '@/components/nav-menu'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body
        // className={inter.className}
        className={clsx(inter.className, 'bg-bg-dark', 'text-font-dark')}
      >
        <NavMenu />
        {children}
      </body>
    </html>
  )
}
