import './globals.css'
import {Inter} from 'next/font/google'
import clsx from 'clsx'
import NavMenu from '@/components/nav-menu'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          inter.className,
          'text-slate-100 container mx-auto md:px-4 py-2 xl:max-w-6xl'
        )}
      >
        <NavMenu />
        {children}
      </body>
    </html>
  )
}
